### ISSUE TITLE
Widget cannot be resized (Windows)

### ISSUE THREAD

**Issue by Pololot64** [IvanHerreraCasas/dynamic_timeline#9]
Hello. I hope you are having a good day. I have DynamicTimeline() in my widget tree in a resizable window. However, when I resize the window, the Dynamic Timeline is the only widget that cannot resize. It crashes with a different error every time. Is this simply unsupported or a bug? Thanks

**Comment by Pololot64** [comment]
I believe it was because of a combination of this widget with the fluent ui library.. I'll close for now. Sorry :)

**Comment by IvanHerreraCasas** [comment]
Hi, 

About resizing, the widget will always take a fixed size in the main axis (using the interval extent, and duration between the last and first date-times) so you need to put it into a singleChildScrollView or similar, and in the cross axis it will depend if you set or not the maxCrossAxisItemExtent (with null can be resized, similar to a flexible widget)

About the errors, that's probably because I haven't added proper error messages or assertions that can prevent or help you identify what is going wrong (unfortunately, I haven't had time).

And well, in my experience, I've had some problems with scroll controllers with fluent UI library and faced some weird errors when updating my widget (DynamicTimeline) without giving keys to each item.

I hope that can help you, and if you find what is causing exactly the error, please let me know (maybe it's a bug that I haven't identified).

**Comment by Pololot64** [comment]
Ah I see. I will edit the cross axis item extent to null and then make my keys manually. I'll let you know what happens

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IvanHerreraCasas** [comment]
Hi, you can take a look at [this example](https://github.com/IvanHerreraCasas/flutter_planner/blob/main/lib/planner/widgets/planner_activities.dart) 
![fp_resize](https://user-images.githubusercontent.com/95146927/212204527-3e5cf49a-b0a9-49d8-bcdc-b86f94cdbe65.gif)

**Comment by Pololot64** [comment]
Hmm... Still no luck. It happens when the fluent NavigationView (which wraps everything) changes the side navigation bar from visible to hidden during resizing (similar to what happens in your example). It still bugs out

https://user-images.githubusercontent.com/31389383/212234861-ea4a4ae6-2d15-4a0b-98a3-f89d3bee84c0.mp4

**Comment by Pololot64** [comment]
I can also cause the error ``` Exception caught by widgets library
'package:flutter/src/foundation/node.dart': Failed assertion: line 112 pos 12: '_owner != null': is not true.
package:flutter/…/foundation/node.dart:112
The relevant error-causing widget was
NavigationView``` 

and '''════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4937 pos 12: 'child == _child': is not true.
package:flutter/…/widgets/framework.dart:4937
The relevant error-causing widget was
NavigationView
lib\navigation_pane.dart:22
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A GlobalKey was used multiple times inside one widget's child list.
The relevant error-causing widget was
NavigationView
lib\navigation_pane.dart:22
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.'''

**Comment by IvanHerreraCasas** [comment]
I have identified a bug not related to resizing but that seems to be occurring in your app and causing the other errors, the fix is not published yet, but can you try it and see if that solves your problem?

Change this in your pubspec.yaml file
```yaml
dependencies:
  dynamic_timeline: 
    git:
      url: https://github.com/IvanHerreraCasas/dynamic_timeline.git
      ref: bug/outdated-items
```

**Comment by Pololot64** [comment]
Awesome. I'll test it.
